name: Node.js CI with Keploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Download Keploy binary
      run: |
        curl -Lo keploy https://github.com/keploy/keploy/releases/download/v0.1.6/keploy-linux-amd64
        chmod +x keploy

    - name: Run API server
      run: |
        nohup npm start & sleep 5

    - name: Run Keploy tests
      run: ./keploy test --proxy-port 5000
