name: Run Keploy Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Download Keploy binary
        run: |
          curl -sSfL https://github.com/keploy/keploy/releases/latest/download/keploy-linux-amd64 -o keploy
          chmod +x keploy

      - name: Run API server in background
        run: |
          nohup npm start > output.log 2>&1 &
          sleep 10

      - name: Run Keploy Tests
        run: ./keploy test --proxy-port 5000
